"use server";

import { getSession } from "@/lib/auth/session";
import { createServiceClient } from "@/lib/supabase/server";

export interface ParentAccessInfo {
  shareToken: string;
  hasPin: boolean;
}

export interface SetParentPinResult {
  success: boolean;
  error?: string;
}

/**
 * Returns the student's share token (always present, generated by the
 * migration) and whether a PIN has been set yet. Admin-only, scoped to
 * the caller's own academy — never leaks tokens across tenants.
 */
export async function getParentAccessInfo(
  studentId: string,
): Promise<ParentAccessInfo | null> {
  const session = await getSession();
  if (!session || session.role !== "admin") return null;

  const supabase = createServiceClient();
  const { data, error } = await supabase
    .from("students")
    .select("parent_share_token, parent_pin_hash, academy_id")
    .eq("id", studentId)
    .single();

  if (error || !data || data.academy_id !== session.academyId) return null;

  return {
    shareToken: data.parent_share_token,
    hasPin: data.parent_pin_hash != null,
  };
}

/**
 * Sets (or resets) a student's parent PIN via the set_parent_pin RPC,
 * which hashes it server-side. Admin-only, scoped to caller's academy.
 */
export async function setParentPinAction(
  studentId: string,
  pin: string,
): Promise<SetParentPinResult> {
  const session = await getSession();
  if (!session || session.role !== "admin") {
    return { success: false, error: "Not authorized." };
  }
  if (!/^\d{4,6}$/.test(pin)) {
    return { success: false, error: "PIN must be 4–6 digits." };
  }

  const supabase = createServiceClient();

  // Ownership check before writing — refuse to set a PIN on a student
  // that doesn't belong to the caller's academy.
  const { data: student, error: fetchError } = await supabase
    .from("students")
    .select("academy_id")
    .eq("id", studentId)
    .single();

  if (fetchError || !student || student.academy_id !== session.academyId) {
    return { success: false, error: "Student not found." };
  }

  const { error } = await supabase.rpc("set_parent_pin", {
    p_student_id: studentId,
    p_pin: pin,
  });

  if (error) return { success: false, error: "Could not set PIN. Try again." };
  return { success: true };
}
